services:
  # Zone A Application Instance
  higiea_zona_a:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      DB_URL: r2dbc:postgresql://zone_a_db/higiea_zone_a_db
      DB_USERNAME: zone_a_user
      DB_PASSWORD: zone_a_pass
      MONGODB_URI: mongodb://mongo:27017/higiea-routes
      MQTT_BROKER_URL: tcp://mqtt:1883
      MQTT_BROKER_TOPIC: sensors/zone_a
    depends_on:
      - zone_a_db
      - mongo
      - mqtt

  # Zone B Application Instance
  higiea_zone_b:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      DB_URL: r2dbc:postgresql://zone_b_db/higiea_zone_b_db
      DB_USERNAME: zone_b_user
      DB_PASSWORD: zone_b_pass
      MONGODB_URI: mongodb://mongo:27017/higiea-routes
      MQTT_BROKER_URL: tcp://mqtt:1883
      MQTT_BROKER_TOPIC: sensors/zone_b
    depends_on:
      - zone_b_db
      - mongo
      - mqtt

  # Shared MongoDB
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config

  # Zone A PostgreSQL
  zone_a_db:
    image: postgres:16
    environment:
      POSTGRES_DB: higiea_zone_a_db
      POSTGRES_USER: zone_a_user
      POSTGRES_PASSWORD: zone_a_pass
    volumes:
      - zone_a_pg_data:/var/lib/postgresql/data

  # Zone B PostgreSQL
  zone_b_db:
    image: postgres:16
    environment:
      POSTGRES_DB: higiea_zone_b_db
      POSTGRES_USER: zone_b_user
      POSTGRES_PASSWORD: zone_b_pass
    volumes:
      - zone_b_pg_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  zone_a_pg_data:
  zone_b_pg_data:
  mosquitto_data:
  mosquitto_config: