DROP TABLE IF EXISTS sensor;
DROP TABLE IF EXISTS truck;
DROP TABLE IF EXISTS route;


CREATE TABLE sensor (
    id SERIAL PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    state VARCHAR(255) NOT NULL
);

CREATE TABLE truck (
    id SERIAL PRIMARY KEY
);
