name: CD Deployment Workflow

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build the application
        run: ./gradlew build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Docker Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/multi-higiea:${{ github.event.release.tag_name }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/multi-higiea:${{ github.event.release.tag_name }}